spring:
  application:
    name: finance
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceServer:
        jwt:
          # https://accounts.google.com/.well-known/openid-configuration
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

allowed-origins: ${ALLOW_URL}
front-url: ${FRONT_URL}
